//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDeEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peliculas
    {
        public int PeliculaId { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public System.DateTime fechaFuncion { get; set; }
        public string Duracion { get; set; }
        public double Precio { get; set; }
    }
}
